spring:
  application:
    name: tech-product-stock-service
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2: 
    console.enabled: true
  security:
    user:
      name: user  
      password: userpass
      

server:
  port: ${port:8808}

jwt:
  secret: secretkey028